# PERFTEST_CMD=
# Specify the perftest command (ib_write_bw, ib_write_lat, ...) 
# the script automatically appends the -q, -p, -s, -d, --tclass and <host> (only for client)
# options with the value configured in following section
# Other options can be confiured here along with the command
#  
# e.g: 
# PERFTEST_CMD='/usr/bin/ib_write_lat -m 1024 --munic-export'
# 
PERFTEST_CMD='ib_write_bw --run_infinitely --report_gbits'

# Specify the mpirun path along with addional arguments, 
# Support absolute and relative path
# e.g: 
# MPIRUN_CMD='/usr/local/bin/mpirun -x DESIRED_ENV_VAR=no_space_value'
MPIRUN_CMD='mpirun'

# List of clients, 
# client format: <hostname>:<nic_device>
# The client order defines pairing with SERVER
CLIENTS='test1:mlx5_0 test1:mlx5_1'

# List of servers, 
# server format: <hostname>:<nic_device>
SERVERS='test2:mlx5_0 test2:mlx5_1'

# The base used to calcuate a unique -p option value for each perftest pair
BASE_PORT=20000

# The QP number, used as the -q option value
QP_NUM=2

# The message size, used as the -s option value
MESSAGE_SIZE=65536

# The traffic class, used as the --tclass option value
TC_CLASS=0

# Set the LD_LIBRARY_PATH environment value used in ompi ranks
# e.g
# CFG_LD_LIBRARY_PATH=/path/to/rdma-core/lib
